version: "3"
services:

#kafka and zookeeeper
  zookeeper-container:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka-container:
    image: confluentinc/cp-kafka
    depends_on: 
      - zookeeper-container
    environment: 
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-container:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-container:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

#Databases

  bestelling_db:
    image: mysql:5.7
    container_name: bestelling_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Bestelling
  magazijn_db:
    image: mysql:5.7
    container_name: magazijn_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Magazijn

#Services
  api-gw:
    build: ./APIGateway
    container_name: api-gw
    links:
      - magazijn-service
      - bestel-service
    depends_on:
      - magazijn-service
      - bestel-service
    ports:
      - 80:8080
  magazijn-service:
    build: ./MagazijnService
    container_name: magazijn-service
    links:
      - magazijn_db
      - kafka-container
    depends_on:
      - magazijn_db
      - kafka-container
  bestel-service:
    build: ./BestelManagement
    container_name: bestel-service
    links:
      - bestelling_db
      - kafka-container
    depends_on:
      - bestelling_db
      - kafka-container
