# Zookeeper
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-container
  template:
    metadata:
      labels:
        app: zookeeper-container
    spec:
      containers:
        - name: zookeeper-container
          image: confluentinc/cp-zookeeper:5.4.1
          ports:
            - containerPort: 2181
          env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-container
  labels:
    app: zookeeper-container
spec:
  type: ClusterIP
  selector:
    app: zookeeper-container
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
---
# Kafka
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-container
  template:
    metadata:
      labels:
        app: kafka-container
    spec:
      containers:
        - name: kafka-container
          image: confluentinc/cp-kafka:5.4.1
          ports:
            - containerPort: 9092
          env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-container:2181"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-container:9092"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-container
  labels:
    app: kafka-container
spec:
  selector:
    app: kafka-container
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP

#BestelManagement
##DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bestel-db
  labels:
    app: bestel-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bestel-db
  template:
    metadata:
      labels:
        app: bestel-db
    spec:
      containers:
      - name: bestel-db
        image: mysql:5.7
        args: ["--default-authentication-plugin=mysql_native_password"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "Bestelling"
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: bestel-db-service
spec:
  selector:
    app: bestel-db
  ports:
    - port: 3306
---
##Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bestel-service
  labels:
    app: bestel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bestel-service
  template:
    metadata:
      labels:
        app: bestel-service
    spec:
      containers:
      - name: bestel-service
        image: alexismartens72/bestelmanagement:v1
        args: ["--spring.datasource.url=jdbc:mysql://bestel-db-service.default.svc.cluster.local:3306/Bestelling"]
---
apiVersion: v1
kind: Service
metadata:
  name: bestel-service
spec:
  selector:
    app: bestel-service
  ports:
    - port: 2000
---
#APIGateway
##Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: toonmertens/apigateway
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: apigateway
  ports:
    - port: 8080
      targetPort: 80
---
